services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "8200:4533"
    environment:
      - PUID=1000   # Saber el PUID/PGID con el comando "id $user"
      - PGID=1000
      - TZ=Europe/Madrid
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_DEFAULTTHEME=Dark   
    volumes:
      - ./data:/data
      - ./music:/music:ro
